services:
  redis:
    image: "redis:7-alpine"
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}